# Site settings
title: Andrew Yan
email: zushenyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write stuffs about web development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zushenyan
github_username:  zushenyan
linkedin_username:  zushenyan


# Build settings
markdown: kramdown

gems:
  - octopress-codefence
  - octopress-solarized
  - octopress-codeblock
  - octopress-image-tag
